name: Deploy

on: [push]
jobs:

  build:
    name: Updating repo
    runs-on: ubuntu-latest
    steps:
    - name: deleting files and cloning new repo
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ../../var/www/html/elliotthiebaut.com/
          rm -rfv {*,.*}
          git clone https://github.com/ElliotThiebaut/elliotthiebaut.com.git .